<?php
/**
 * DataProvidersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CBRAIN API
 *
 * API for interacting with the CBRAIN Platform
 *
 * OpenAPI spec version: 5.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DataProvidersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DataProvidersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for dataProvidersGet
     *
     * Get a list of the Data Providers available to the current user..
     *
     */
    public function testDataProvidersGet()
    {
    }

    /**
     * Test case for dataProvidersIdBrowseGet
     *
     * List the files on a Data Provider..
     *
     */
    public function testDataProvidersIdBrowseGet()
    {
    }

    /**
     * Test case for dataProvidersIdDeletePost
     *
     * Deletes unregistered files from a CBRAIN Data provider..
     *
     */
    public function testDataProvidersIdDeletePost()
    {
    }

    /**
     * Test case for dataProvidersIdGet
     *
     * Get information on a particular Data Provider..
     *
     */
    public function testDataProvidersIdGet()
    {
    }

    /**
     * Test case for dataProvidersIdIsAliveGet
     *
     * Pings a Data Provider to check if it is running..
     *
     */
    public function testDataProvidersIdIsAliveGet()
    {
    }

    /**
     * Test case for dataProvidersIdRegisterPost
     *
     * Registers a file as a Userfile in CBRAIN..
     *
     */
    public function testDataProvidersIdRegisterPost()
    {
    }

    /**
     * Test case for dataProvidersIdUnregisterPost
     *
     * Unregisters files as Userfile in CBRAIN..
     *
     */
    public function testDataProvidersIdUnregisterPost()
    {
    }
}
