<?php
/**
 * GroupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CBRAIN API
 *
 * API for interacting with the CBRAIN Platform
 *
 * OpenAPI spec version: 5.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * GroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for groupsGet
     *
     * Get a list of the Groups (projects) available to the current user..
     *
     */
    public function testGroupsGet()
    {
    }

    /**
     * Test case for groupsIdDelete
     *
     * Deletes a Group (project)..
     *
     */
    public function testGroupsIdDelete()
    {
    }

    /**
     * Test case for groupsIdGet
     *
     * Get information on a Group (project)..
     *
     */
    public function testGroupsIdGet()
    {
    }

    /**
     * Test case for groupsIdPut
     *
     * Update the properties of a Group (project)..
     *
     */
    public function testGroupsIdPut()
    {
    }

    /**
     * Test case for groupsPost
     *
     * Creates a new Group..
     *
     */
    public function testGroupsPost()
    {
    }
}
