<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CBRAIN API
 *
 * REST API for interacting with the CBRAIN Platform
 *
 * OpenAPI spec version: 5.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UsersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for usersGet
     *
     * Returns all of the users in CBRAIN..
     *
     */
    public function testUsersGet()
    {
    }

    /**
     * Test case for usersIdDelete
     *
     * Deletes a CBRAIN user.
     *
     */
    public function testUsersIdDelete()
    {
    }

    /**
     * Test case for usersIdGet
     *
     * Returns information about a user.
     *
     */
    public function testUsersIdGet()
    {
    }

    /**
     * Test case for usersIdPatch
     *
     * Update information about a user.
     *
     */
    public function testUsersIdPatch()
    {
    }

    /**
     * Test case for usersPost
     *
     * Create a new user in CBRAIN..
     *
     */
    public function testUsersPost()
    {
    }
}
