<?php
/**
 * UserfilesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CBRAIN API
 *
 * API for interacting with the CBRAIN Platform
 *
 * OpenAPI spec version: 5.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UserfilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserfilesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for userfilesChangeProviderPost
     *
     * Moves the Userfiles from their current Data Provider to a new one..
     *
     */
    public function testUserfilesChangeProviderPost()
    {
    }

    /**
     * Test case for userfilesCompressPost
     *
     * Compresses many Userfiles each into their own GZIP archive..
     *
     */
    public function testUserfilesCompressPost()
    {
    }

    /**
     * Test case for userfilesDeleteFilesDelete
     *
     * Delete several files that have been registered as Userfiles.
     *
     */
    public function testUserfilesDeleteFilesDelete()
    {
    }

    /**
     * Test case for userfilesDownloadPost
     *
     * Download several files.
     *
     */
    public function testUserfilesDownloadPost()
    {
    }

    /**
     * Test case for userfilesGet
     *
     * List of the Userfiles accessible to the current user..
     *
     */
    public function testUserfilesGet()
    {
    }

    /**
     * Test case for userfilesIdContentGet
     *
     * Get the content of a Userfile.
     *
     */
    public function testUserfilesIdContentGet()
    {
    }

    /**
     * Test case for userfilesIdGet
     *
     * Get information on a Userfile..
     *
     */
    public function testUserfilesIdGet()
    {
    }

    /**
     * Test case for userfilesIdPut
     *
     * Update information on a Userfile..
     *
     */
    public function testUserfilesIdPut()
    {
    }

    /**
     * Test case for userfilesPost
     *
     * Creates a new Userfile and upload its content..
     *
     */
    public function testUserfilesPost()
    {
    }

    /**
     * Test case for userfilesSyncMultiplePost
     *
     * Syncs Userfiles to the local Data Providers cache..
     *
     */
    public function testUserfilesSyncMultiplePost()
    {
    }

    /**
     * Test case for userfilesUncompressPost
     *
     * Uncompresses many Userfiles..
     *
     */
    public function testUserfilesUncompressPost()
    {
    }
}
